# -*- coding: utf-8 -*-
"""Assignment - 3 Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14sW4QpLl2wW4SBmJvuge4ifqetS6sXat
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

df = pd.read_csv('/content/ITC-EQ-01-04-2000-to-31-03-2024.csv')

df

df.head()

df.info()

df.isnull().sum()

df = df.dropna()

import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df.index,
    y=df['close'],
    mode='lines',
    name='Closing Price'
))

fig.update_layout(
    title='Stock Closing Price Trend',
    xaxis_title='Date',
    yaxis_title='Price'
)

fig.show()

import pandas as pd
import plotly.graph_objects as go
import os # Import os module

# Re-load and preprocess df to ensure it's defined and correctly structured.
# The files.upload() output confirms the file was saved as '/content/ITC-EQ-01-04-2000-to-31-03-2024.csv'.
file_path = '/content/ITC-EQ-01-04-2000-to-31-03-2024.csv' # Updated to the correct uploaded filename

# Check if the file exists before attempting to read it
if not os.path.exists(file_path):
    raise FileNotFoundError(
        f"The file '{file_path}' was not found. Please ensure it is uploaded "
        "to the /content/ directory and the path is correct. If you just uploaded it, "
        "you might need to re-run the upload cell (479e9a4c) and then this cell."
    )

df = pd.read_csv(file_path)
df = df.dropna()

if 'date' in df.columns:
    df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
    df = df.set_index('date')

df['MA50'] = df['close'].rolling(window=50).mean()

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df.index,
    y=df['close'],
    mode='lines',
    name='Close Price'
))

fig.add_trace(go.Scatter(
    x=df.index,
    y=df['MA50'],
    mode='lines',
    name='50-Day MA'
))

fig.update_layout(
    title='Close Price vs Moving Average'
)

fig.show()

df.to_csv("stock_dashboard_output.csv")

print(df.columns)

if 'date' in df.columns:
    df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
    df = df.set_index('date')

# Calculate KPIs
current_price = df['close'].iloc[-1]
fifty_two_week_high = df['high'].rolling(window=252).max().iloc[-1] # Assuming 252 trading days in a year
fifty_two_week_low = df['low'].rolling(window=252).min().iloc[-1]   # Assuming 252 trading days in a year
average_volume = df['volume'].mean()

print(f"Current Price: {current_price:.2f}")
print(f"52-Week High: {fifty_two_week_high:.2f}")
print(f"52-Week Low: {fifty_two_week_low:.2f}")
print(f"Average Volume: {average_volume:.2f}")

!pip install dash dash-core-components dash-html-components # Install Dash and its components

import dash
from dash.dependencies import Input, Output, State # Added State for date range inputs
from dash import dcc
from dash import html
import plotly.graph_objects as go
import pandas as pd
import numpy as np
import nest_asyncio # Import nest_asyncio for Colab inline display
import threading # Import threading to run Dash app in a separate thread
import time # Import time for a brief pause
from google.colab import output # Import output for inline display
import os # Import os module

# --- Data Loading and Preprocessing (Copied from previous cells to make this cell self-contained) ---
# The files.upload() output confirms the file was saved as '/content/ITC-EQ-01-04-2000-to-31-03-2024.csv'.
file_path = '/content/ITC-EQ-01-04-2000-to-31-03-2024.csv' # Corrected back to the original uploaded filename

# Check if the file exists before attempting to read it
if not os.path.exists(file_path):
    raise FileNotFoundError(
        f"The file '{file_path}' was not found. Please ensure it is uploaded "
        "to the /content/ directory and the path is correct. If you just uploaded it, "
        "you might need to re-run the upload cell (479e9a4c) and then this cell."
    )

df = pd.read_csv(file_path)
df = df.dropna()

if 'date' in df.columns:
    df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
    df = df.set_index('date')

# Calculate KPIs
current_price = df['close'].iloc[-1]
fifty_two_week_high = df['high'].rolling(window=252).max().iloc[-1] # Assuming 252 trading days in a year
fifty_two_week_low = df['low'].rolling(window=252).min().iloc[-1]   # Assuming 252 trading days in a year
average_volume = df['volume'].mean()

# Data Preparation for Charts
# 1. Daily Price Change for Pie Chart
df['Daily_Change'] = df['close'].diff()
df['Change_Category'] = df['Daily_Change'].apply(lambda x: 'Positive' if x > 0 else ('Negative' if x < 0 else 'No Change'))
change_counts = df['Change_Category'].value_counts()

# 2. Correlation Matrix for Heatmap
correlation_cols = ['open', 'high', 'low', 'close', 'volume']
correlation_df = df[correlation_cols].corr()

# Initialize the Dash app
app = dash.Dash(__name__) # Use dash.Dash directly

# Define the layout of the dashboard
app.layout = html.Div(style={'fontFamily': 'Arial, sans-serif', 'backgroundColor': '#f8f9fa', 'padding': '20px'},
    children=[
        # Top Section: Title + KPIs
        html.Div(style={'display': 'flex', 'flexDirection': 'column', 'alignItems': 'center', 'marginBottom': '30px'},
            children=[
                html.H1("ITC Stock Performance Dashboard", style={'color': '#343a40', 'fontSize': '2.5em', 'marginBottom': '20px'}),
                html.Div(style={'display': 'flex', 'justifyContent': 'space-around', 'width': '100%', 'maxWidth': '1200px'},
                    children=[
                        html.Div(className='kpi-card', style={'backgroundColor': '#ffffff', 'borderRadius': '8px', 'boxShadow': '0 4px 8px rgba(0,0,0,0.1)', 'padding': '20px', 'margin': '10px', 'flex': '1', 'textAlign': 'center'},
                            children=[
                                html.H3("Current Price", style={'color': '#007bff', 'marginBottom': '10px'}),
                                html.P(f"${current_price:.2f}", style={'fontSize': '1.8em', 'fontWeight': 'bold'})
                            ]
                        ),
                        html.Div(className='kpi-card', style={'backgroundColor': '#ffffff', 'borderRadius': '8px', 'boxShadow': '0 4px 8px rgba(0,0,0,0.1)', 'padding': '20px', 'margin': '10px', 'flex': '1', 'textAlign': 'center'},
                            children=[
                                html.H3("52-Week High", style={'color': '#28a745', 'marginBottom': '10px'}),
                                html.P(f"${fifty_two_week_high:.2f}", style={'fontSize': '1.8em', 'fontWeight': 'bold'})
                            ]
                        ),
                        html.Div(className='kpi-card', style={'backgroundColor': '#ffffff', 'borderRadius': '8px', 'boxShadow': '0 4px 8px rgba(0,0,0,0.1)', 'padding': '20px', 'margin': '10px', 'flex': '1', 'textAlign': 'center'},
                            children=[
                                html.H3("52-Week Low", style={'color': '#dc3545', 'marginBottom': '10px'}),
                                html.P(f"${fifty_two_week_low:.2f}", style={'fontSize': '1.8em', 'fontWeight': 'bold'})
                            ]
                        ),
                        html.Div(className='kpi-card', style={'backgroundColor': '#ffffff', 'borderRadius': '8px', 'boxShadow': '0 4px 8px rgba(0,0,0,0.1)', 'padding': '20px', 'margin': '10px', 'flex': '1', 'textAlign': 'center'},
                            children=[
                                html.H3("Average Volume", style={'color': '#6c757d', 'marginBottom': '10px'}),
                                html.P(f"{average_volume:,.0f}", style={'fontSize': '1.8em', 'fontWeight': 'bold'})
                            ]
                        )
                    ]
                )
            ]
        ),

        # Date Range Filter and Download Button
        html.Div(style={'width': '80%', 'margin': '20px auto', 'textAlign': 'center', 'backgroundColor': '#ffffff', 'borderRadius': '8px', 'boxShadow': '0 4px 8px rgba(0,0,0,0.1)', 'padding': '15px'},
            children=[
                html.Label("Select Date Range:", style={'marginRight': '10px', 'fontWeight': 'bold', 'color': '#343a40'}),
                dcc.DatePickerRange(
                    id='date-range-picker',
                    start_date=df.index.min().strftime('%Y-%m-%d'),
                    end_date=df.index.max().strftime('%Y-%m-%d'),
                    display_format='DD-MM-YYYY'
                ),
                html.Button('Download Filtered Data', id='download-button', style={'marginLeft': '20px', 'backgroundColor': '#007bff', 'color': 'white', 'border': 'none', 'padding': '10px 20px', 'borderRadius': '5px', 'cursor': 'pointer'}),
                dcc.Download(id='download-dataframe-csv') # Download component
            ]
        ),

        # Middle Section: 2 Charts
        html.Div(style={'display': 'flex', 'justifyContent': 'space-around', 'flexWrap': 'wrap', 'marginBottom': '20px'},
            children=[
                html.Div(style={'width': '48%', 'minWidth': '400px', 'margin': '10px', 'backgroundColor': '#ffffff', 'borderRadius': '8px', 'boxShadow': '0 4px 8px rgba(0,0,0,0.1)'},
                    children=[
                        dcc.Graph(id='line-chart-close')
                    ]
                ),
                html.Div(style={'width': '48%', 'minWidth': '400px', 'margin': '10px', 'backgroundColor': '#ffffff', 'borderRadius': '8px', 'boxShadow': '0 4px 8px rgba(0,0,0,0.1)'},
                    children=[
                        dcc.Graph(id='bar-chart-volume')
                    ]
                )
            ]
        ),

        # Bottom Section: 2 More Charts
        html.Div(style={'display': 'flex', 'justifyContent': 'space-around', 'flexWrap': 'wrap'},
            children=[
                html.Div(style={'width': '48%', 'minWidth': '400px', 'margin': '10px', 'backgroundColor': '#ffffff', 'borderRadius': '8px', 'boxShadow': '0 4px 8px rgba(0,0,0,0.1)'},
                    children=[
                        dcc.Graph(id='pie-chart-changes')
                    ]
                ),
                html.Div(style={'width': '48%', 'minWidth': '400px', 'margin': '10px', 'backgroundColor': '#ffffff', 'borderRadius': '8px', 'boxShadow': '0 4px 8px rgba(0,0,0,0.1)'},
                    children=[
                        dcc.Graph(id='heatmap-correlation')
                    ]
                )
            ]
        )
    ]
)

# Callbacks to update charts based on date range filter
@app.callback(
    [Output('line-chart-close', 'figure'),
     Output('bar-chart-volume', 'figure'),
     Output('pie-chart-changes', 'figure'),
     Output('heatmap-correlation', 'figure')],
    [Input('date-range-picker', 'start_date'),
     Input('date-range-picker', 'end_date')]
)
def update_charts(start_date, end_date):
    filtered_df = df.loc[start_date:end_date] if start_date and end_date else df

    # Line Chart: Closing Price Trend
    line_fig = go.Figure(data=[
        go.Scatter(x=filtered_df.index, y=filtered_df['close'], mode='lines', name='Closing Price')
    ])
    line_fig.update_layout(
        title='Stock Closing Price Trend',
        xaxis_title='Date',
        yaxis_title='Price (INR)',
        margin=dict(l=40, r=40, t=40, b=40)
    )

    # Bar Chart: Daily Volume
    bar_fig = go.Figure(data=[
        go.Bar(x=filtered_df.index, y=filtered_df['volume'], name='Daily Volume', marker_color='#4CAF50')
    ])
    bar_fig.update_layout(
        title='Daily Trading Volume',
        xaxis_title='Date',
        yaxis_title='Volume',
        margin=dict(l=40, r=40, t=40, b=40)
    )

    # Pie Chart: Daily Price Change Distribution
    # Recalculate change categories for the filtered data
    filtered_df['Daily_Change'] = filtered_df['close'].diff()
    filtered_df['Change_Category'] = filtered_df['Daily_Change'].apply(lambda x: 'Positive' if x > 0 else ('Negative' if x < 0 else 'No Change'))
    filtered_change_counts = filtered_df['Change_Category'].value_counts()

    pie_fig = go.Figure(data=[
        go.Pie(
            labels=filtered_change_counts.index,
            values=filtered_change_counts.values,
            hole=0.3,
            marker_colors=['#28a745', '#dc3545', '#6c757d']
        )
    ])
    pie_fig.update_layout(
        title='Daily Price Change Distribution',
        margin=dict(l=40, r=40, t=40, b=40)
    )

    # Heatmap: Correlation Matrix
    filtered_correlation_df = filtered_df[correlation_cols].corr()
    heatmap_fig = go.Figure(data=[
        go.Heatmap(
            z=filtered_correlation_df.values,
            x=filtered_correlation_df.columns,
            y=filtered_correlation_df.columns,
            colorscale='Viridis'
        )
    ])
    heatmap_fig.update_layout(
        title='Correlation Matrix of Stock Metrics',
        xaxis_title='Metric',
        yaxis_title='Metric',
        margin=dict(l=40, r=40, t=40, b=40)
    )

    return line_fig, bar_fig, pie_fig, heatmap_fig

# New callback for download button
@app.callback(
    Output('download-dataframe-csv', 'data'),
    Input('download-button', 'n_clicks'),
    State('date-range-picker', 'start_date'),
    State('date-range-picker', 'end_date'),
    prevent_initial_call=True # Prevent immediate download on app load
)
def download_csv(n_clicks, start_date, end_date):
    if n_clicks:
        # Re-filter the DataFrame based on current date range
        filtered_df = df.loc[start_date:end_date] if start_date and end_date else df
        # Use dcc.send_data_frame to send the CSV data for download
        return dcc.send_data_frame(filtered_df.to_csv, "itc_filtered_data.csv")
    return None # Return None if button not clicked


# Run the app
if __name__ == '__main__':
    nest_asyncio.apply() # Apply nest_asyncio for inline display in Colab
    port = 8050 # Or any available port

    # Start the Dash app in a separate thread
    def run_dash_app():
        # Set debug=False and use_reloader=False to avoid the signal handler error in a non-main thread
        app.run(debug=False, use_reloader=False, port=port, dev_tools_hot_reload=False)

    thread = threading.Thread(target=run_dash_app)
    time.sleep(5) # Wait a moment for the server to start
    thread.start()

    # Serve the kernel port as an iframe
    output.serve_kernel_port_as_iframe(port)

from google.colab import output
port = 8050 # The port where the Dash app is running
output.serve_kernel_port_as_iframe(port)
from google.colab import output
output.serve_kernel_port_as_window(5000)

from google.colab import output
output.serve_kernel_port_as_window(5000)